# When adding new food also add to random spawner located in Resources\Prototypes\Entities\Markers\Spawners\Random\Food_Drinks\food_produce.yml

- type: entity
  parent: FoodProduceBase
  id: FoodCrudcoaPod
  name: crudcoa pod
  description: A pod-shaped ball of varying dull, grey plastics. You could almost use this as a basketball!
  components:
  - type: FlavorProfile
    flavors:
    - plastic
  - type: Solution
    solution:
      reagents:
      - ReagentId: Oil
        Quantity: 5
      - ReagentId: Phosphorus
        Quantity: 5
  - type: Sprite
    sprite: _Carpmosia/Objects/Specific/Hydroponics/crudcoa.rsi
  - type: Produce
    seedId: crudcoa
  - type: ToolRefinable
    qualityNeeded: Sawing
    refineResult:
    - id: SheetPlastic1
  - type: PhysicalComposition
    materialComposition:
      Plastic: 100
- type: entity
  parent: FoodProduceBase
  id: FoodCharrot
  name: charrot
  description: A carrot-shaped coal formation, it bears an odd resemblance to a drill.
  components:
  - type: FlavorProfile
    flavors:
    - chalky
  - type: Solution
    solution:
      reagents:
      - ReagentId: Carbon
        Quantity: 8.4
      - ReagentId: Ammonia
        Quantity: 0.8
      - ReagentId: Hydrogen
        Quantity: 0.5
      - ReagentId: Sulfur
        Quantity: 0.2
      - ReagentId: Mercury
        Quantity: 0.1
  - type: Sprite
    sprite: _Carpmosia/Objects/Specific/Hydroponics/charrot.rsi
  - type: Produce
    seedId: charrots
  - type: Tag
    tags:
    - Carrot
    - Vegetable
  - type: Damageable
  - type: Injurable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 15
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: GlassBreak
          params:
            volume: -4
      - !type:SpawnEntitiesBehavior
        spawn:
          Coal:
            min: 1
            max: 3
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: DamageOnHit
    damage:
      types:
        Structural: 15
        Piercing: 5
  - type: MeleeWeapon
    wideAnimationRotation: 0
    damage:
      types:
        Structural: 15
        Piercing: 5
    soundHit:
        path: /Audio/Items/Mining/pickaxe.ogg
  - type: PhysicalComposition
    materialComposition:
      Coal: 100
